# Server configuration
server.port=${PORT:8080}

# MongoDB Configuration
# We use the environment variable if present (best for Render), or fallback to the hardcoded URI
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://gtprashanth2_db_user:Prashanth123@cluster0.ybhm0zd.mongodb.net/compiler_db?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.auto-index-creation=true

# JWT configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# File upload limits
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

